name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'  # Match version tags, e.g., v1.0.0

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        include:
          - goos: linux
            goarch: amd64
            dir: dist/linux
            extension: ""
          - goos: linux
            goarch: arm64
            dir: dist/linux
            extension: ""
          - goos: windows
            goarch: amd64
            dir: dist/win
            extension: ".exe"
          - goos: windows
            goarch: arm64
            dir: dist/win
            extension: ".exe"
          - goos: darwin
            goarch: amd64
            dir: dist/macos
            extension: ""
          - goos: darwin
            goarch: arm64
            dir: dist/macos
            extension: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
          cache: false

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o ${{ matrix.dir }}/rune-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension }} ./dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rune-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist

      - name: Log Upload Artifacts
        run: |
          echo "Uploaded artifacts:"
          ls -l dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List Downloaded Artifacts
        run: |
          echo "Listing contents of the dist directory:"
          ls -R dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Linux Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/rune-linux-amd64
          asset_name: rune-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/rune-windows-amd64.exe
          asset_name: rune-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload MacOS Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/rune-darwin-amd64
          asset_name: rune-darwin-amd64
          asset_content_type: application/octet-stream
